# True to enable all resources
RESOURCES_ALL = True

# Available resources
RESOURCES = [
		"adblue_level",
        "aircon_at_unlock",
		"auxiliary_climatisation",
		"battery_level",
		"charge_max_ampere",
		"charger_action_status",
		"charging",
        "charge_rate",
        "charging_power",
		"charging_cable_connected",
		"charging_cable_locked",
		"charging_time_left",
		"climater_action_status",
		"climatisation_target_temperature",
		"climatisation_without_external_power",
		"combined_range",
		"combustion_range",
        "departure1",
        "departure2",
        "departure3",
		"distance",
		"door_closed_left_back",
		"door_closed_left_front",
		"door_closed_right_back",
		"door_closed_right_front",
		"door_locked",
		"electric_climatisation",
		"electric_range",
		"energy_flow",
		"external_power",
		"fuel_level",
		"hood_closed",
		"last_connected",
		"lock_action_status",
        "model",
		"oil_inspection",
		"oil_inspection_distance",
		"outside_temperature",
		"parking_light",
		"parking_time",
		"pheater_heating",
		"pheater_status",
		"pheater_ventilation",
        "plug_autounlock",
		"position",
		"refresh_action_status",
		"refresh_data",
        "request_flash",
        "request_honkandflash",
		"request_in_progress",
		"request_results",
		"requests_remaining",
        "seat_heating_front_left",
        "seat_heating_front_right",
        "seat_heating_rear_left",
        "seat_heating_rear_right",
		"service_inspection",
		"service_inspection_distance",
		"sunroof_closed",
		"trip_last_average_auxillary_consumption",
        "trip_last_average_aux_consumer_consumption",
		"trip_last_average_electric_consumption",
		"trip_last_average_fuel_consumption",
        "trip_last_average_recuperation",
		"trip_last_average_speed",
		"trip_last_duration",
		"trip_last_entry",
		"trip_last_length",
		"trip_last_recuperation",
		"trip_last_total_electric_consumption",
        "trip_last_start_mileage",
		"trip_longterm_average_auxillary_consumption",
        "trip_longterm_average_aux_consumer_consumption",
		"trip_longterm_average_electric_consumption",
		"trip_longterm_average_fuel_consumption",
        "trip_longterm_average_recuperation",
		"trip_longterm_average_speed",
		"trip_longterm_duration",
		"trip_longterm_entry",
		"trip_longterm_length",
		"trip_longterm_recuperation",
		"trip_longterm_total_electric_consumption",
        "trip_longterm_start_mileage",
		"trunk_closed",
		"trunk_locked",
		"vehicle_moving",
		"window_closed_left_back",
		"window_closed_left_front",
		"window_closed_right_back",
		"window_closed_right_front",
		"window_heater",
        "window_heater_new",
		"windows_closed",
        "seat_heating"
]

COMPONENTS = {
    'sensor': 'sensor',
    'binary_sensor': 'binary_sensor',
    'lock': 'lock',
    'device_tracker': 'device_tracker',
    'switch': 'switch',
}


def is_enabled(attr):
    """Return true if the user has enabled the resource."""
    if RESOURCES_ALL is True:
        return True
    return attr in RESOURCES